# LIGHTS #######################################################################
sun_light_time_setting:
    name: Heure départ lumière 
    icon: mdi:lightbulb-group
    has_date: false
    has_time: true
sun_light_time_dusk:
    name: Heure luminosité maximale 
    icon: mdi:lightbulb-group
    has_date: false
    has_time: true
sun_light_time_midnight:
    name: Heure luminosité minimale 
    icon: mdi:lightbulb-group
    has_date: false
    has_time: true
sun_light_time_dawn:
    name: Heure luminosité à l'aube
    icon: mdi:lightbulb-group
    has_date: false
    has_time: true
sun_light_time_dawn_angle:
    name: Heure angle luminosité à l'aube
    icon: mdi:lightbulb-group
    has_date: false
    has_time: true
sun_light_time_rising:
    name: Heure luminosité arrêt lumière
    icon: mdi:lightbulb-group
    has_date: false
    has_time: true
speaker_day_mode_start:
    icon: mdi:speaker
    has_date: false
    has_time: true
speaker_night_mode_start:
    icon: mdi:speaker
    has_date: false
    has_time: true
