################################################################################
  - platform: template
    switches:
      heat:
        friendly_name: Chauffage
        value_template: "{{ is_state('input_boolean.heat', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.heat
        turn_off:
          service: input_boolean.turn_off
          data:
            entity_id: input_boolean.heat
################################################################################
  - platform: template
    switches:
      autolights:
        friendly_name: Lumières automatique
        value_template: "{{ is_state('input_boolean.autolights', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.autolights
        turn_off:
          service: input_boolean.turn_off
          data:
            entity_id: input_boolean.autolights
################################################################################
  - platform: template
    switches:
      light_when_cloudy:
        friendly_name: Lumière anti-nuages
        value_template: "{{ is_state('input_boolean.light_when_cloudy', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.light_when_cloudy
        turn_off:
          service: input_boolean.turn_off
          data:
            entity_id: input_boolean.light_when_cloudy
################################################################################
  - platform: template
    switches:
      stores_auto:
        friendly_name: Volets automatiques
        value_template: "{{ is_state('input_boolean.stores_auto', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.stores_auto
        turn_off:
          service: input_boolean.turn_off
          data:
            entity_id: input_boolean.stores_auto            
            