################################################################################
water_heat_pct:
  icon: mdi:water-boiler
  name: Pourcentage en heures creuses
  min: 0
  max: 100
  unit_of_measurement: '%'
water_heat_duration:
  icon: mdi:av-timer
  name: Temps d'activation manuel
  min: 0
  max: 360
  unit_of_measurement: 'min'
water_heat_person_number:
    min: 1
    max: 8
water_heat_adjustment:
    min: -10
    max: 10
################################################################################
temp_ext:
  name: Mesure température exterieure
  min: -40
  max: 70
  step: 0.1
  unit_of_measurement: '°'
################################################################################  
temp_int_1:
  name: Mesure température interieure 1
  min: -40
  max: 70
  step: 0.1
  unit_of_measurement: '°'
temp_int_2:
  name: Mesure température interieure 2
  min: -40
  max: 70
  step: 0.1
  unit_of_measurement: '°'
temp_int_3:
  name: Mesure température interieure 3
  min: -40
  max: 70
  step: 0.1
  unit_of_measurement: '°'
temp_int_4:
  name: Mesure température interieure 4
  min: -40
  max: 70
  step: 0.1
  unit_of_measurement: '°'
temp_int_5:
  name: Mesure température interieure 5
  min: -40
  max: 70
  step: 0.1
  unit_of_measurement: '°'
temp_int_6:
  name: Mesure température interieure 6
  min: -40
  max: 70
  step: 0.1
  unit_of_measurement: '°'
temp_int_7:
  name: Mesure température interieure 7
  min: -40
  max: 70
  step: 0.1
  unit_of_measurement: '°'
temp_int_8:
  name: Mesure température interieure 8
  min: -40
  max: 70
  step: 0.1
  unit_of_measurement: '°'
temp_int_9:
  name: Mesure température interieure 9
  min: -40
  max: 70
  step: 0.1
  unit_of_measurement: '°'
temp_int_10:
  name: Mesure température interieure 10
  min: -40
  max: 70
  step: 0.1
  unit_of_measurement: '°'
################################################################################
humidity_ext:
  name: Mesure humidité exterieure
  min: 0
  max: 100
  step: 0.1
  unit_of_measurement: '%'
################################################################################
humidity_int_1:
  name: Mesure humidité interieure 1
  min: 0
  max: 100
  step: 0.1
  unit_of_measurement: '%'
humidity_int_2:
  name: Mesure humidité interieure 2
  min: 0
  max: 100
  step: 0.1
  unit_of_measurement: '%'
humidity_int_3:
  name: Mesure humidité interieure 3
  min: 0
  max: 100
  step: 0.1
  unit_of_measurement: '%'
humidity_int_4:
  name: Mesure humidité interieure 4
  min: 0
  max: 100
  step: 0.1
  unit_of_measurement: '%'
humidity_int_5:
  name: Mesure humidité interieure 5
  min: 0
  max: 100
  step: 0.1
  unit_of_measurement: '%'
humidity_int_6:
  name: Mesure humidité interieure 6
  min: 0
  max: 100
  step: 0.1
  unit_of_measurement: '%'
humidity_int_7:
  name: Mesure humidité interieure 7
  min: 0
  max: 100
  step: 0.1
  unit_of_measurement: '%'
humidity_int_8:
  name: Mesure humidité interieure 8
  min: 0
  max: 100
  step: 0.1
  unit_of_measurement: '%'
humidity_int_9:
  name: Mesure humidité interieure 9
  min: 0
  max: 100
  step: 0.1
  unit_of_measurement: '%'
humidity_int_10:
  name: Mesure humidité interieure 10
  min: 0
  max: 100
  step: 0.1
  unit_of_measurement: '%'
################################################################################
sun_angle_light_on:
  name: Angle du soleil départ lumières
  icon: mdi:weather-sunset-down
  min: 0
  max: 20
  unit_of_measurement: '°'
sun_angle_light_off:
  name: Angle du soleil arrêt lumières
  icon: mdi:weather-sunset-up
  min: 0
  max: 20
  unit_of_measurement: '°'
elevation:
  min: -100
  max: 100
  unit_of_measurement: '°'
color_rotate:
  name: Couleur lorsque la lumière s'éteint
  icon: mdi:palette
  min: 0
  max: 360
  unit_of_measurement: '°'
cloudy_light:
  name: Lumière anti-nuages
  icon: mdi:cloud-off-outline
  min: 50
  max: 4000
  unit_of_measurement: 'Lux'
illuminance_light:
  name: Luminosité extérieure
  icon: mdi:theme-light-dark
  min: 0
  max: 100000
  unit_of_measurement: 'Lux'
################################################################################
sun_angle_cover_on:
  name: Angle du soleil ouverture volets
  icon: mdi:weather-sunset-up
  min: -15
  max: 15
  unit_of_measurement: '°'
sun_angle_cover_off:
  name: Angle du soleil fermeture volets
  icon: mdi:weather-sunset-up
  min: -15
  max: 15
  unit_of_measurement: '°'
################################################################################
temp_min:
  name: Température basse d'alerte
  icon: mdi:home-thermometer-outline
  min: 18
  max: 22
  unit_of_measurement: '°C'
temp_max:
  name: Température haute d'alerte
  icon: mdi:home-thermometer-outline
  min: 22
  max: 26
  unit_of_measurement: '°C'
humidity_min:
  name: Humidité basse d'alerte
  icon: mdi:water-percent
  min: 0
  max: 100
  unit_of_measurement: '%'
humidity_max:
  name: Humidité haute d'alerte
  icon: mdi:water-percent
  min: 0
  max: 100
  unit_of_measurement: '%'
################################################################################
low_batteries:
  name: Alerte batteries faibles
  icon: mdi:battery-alert-variant-outline
  min: 5
  max: 30
  step: 1
  unit_of_measurement: '%'
################################################################################
speaker_day_mode_volume:
  name: Volume en mode jour
  icon: mdi:volume-high
  min: 0
  max: 100
  step: 1
  unit_of_measurement: '%'
speaker_night_mode_volume:
  name: Volume en mode nuit
  icon: mdi:volume-medium
  min: 0
  max: 100
  step: 1
  unit_of_measurement: '%'